/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPlay = new javax.swing.JButton();
        jButtonInstrucciones = new javax.swing.JButton();
        jButtonControles = new javax.swing.JButton();
        jLabelImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jugarpeque.png"))); // NOI18N
        jButtonPlay.setContentAreaFilled(false);
        jButtonPlay.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jugarpeque.png"))); // NOI18N
        jButtonPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jugar.png"))); // NOI18N
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 180, 170));

        jButtonInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonInstruccionespeque.png"))); // NOI18N
        jButtonInstrucciones.setContentAreaFilled(false);
        jButtonInstrucciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonInstruccionespeque.png"))); // NOI18N
        jButtonInstrucciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonInstrucciones.png"))); // NOI18N
        jButtonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 300, 80));

        jButtonControles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonControlespeque.png"))); // NOI18N
        jButtonControles.setContentAreaFilled(false);
        jButtonControles.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonControlespeque.png"))); // NOI18N
        jButtonControles.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonControles.png"))); // NOI18N
        jButtonControles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControlesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonControles, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 250, 60));

        jLabelImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.png"))); // NOI18N
        getContentPane().add(jLabelImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonControlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControlesActionPerformed
       Controles controles=new Controles();
       this.setVisible(false);
       controles.setVisible(true);
    }//GEN-LAST:event_jButtonControlesActionPerformed

    private void jButtonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstruccionesActionPerformed
        Instrucciones ins=new Instrucciones();
        this.setVisible(false);
        ins.setVisible(true);
    }//GEN-LAST:event_jButtonInstruccionesActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
            ModoDeJuego mdj=new ModoDeJuego();
            this.setVisible(false);
            mdj.setVisible(true);
    }//GEN-LAST:event_jButtonPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonControles;
    private javax.swing.JButton jButtonInstrucciones;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JLabel jLabelImagenFondo;
    // End of variables declaration//GEN-END:variables
}
